[project]
name = "sms-notifier-workspace"
version = "0.2.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "sms-notifier-client",
    "sms-notifier-server",
]

[dependency-groups]
dev = ["pytest>=8.4.0,<9"]

[tool.uv.sources]
sms-notifier-client = { workspace = true }
sms-notifier-server = { workspace = true }

[tool.uv.workspace]
members = ["client", "server"]

[tool.pytest.ini_options]
testpaths = ["tests"]
